### ISSUE TITLE
Tremor camera bug

### ISSUE THREAD

**Issue by Alpha2546** [Legion-Expansion/Legion-Expansion#324]
When you use chronocam or after chronocam (when you reload from an earlier point) the shaky camera bugs out the camera view. It'll keep on switching into the middle of space when Tremor attacks.

**Comment by Alpha2546** [comment]
I don't think this can be fixed. I think this is a uberbug. Thankfully it only happens when you use chrono resume

**Comment by Alpha2546** [comment]
Why was this closed? It needs more testing. Might be fixed might not be able to be fixed. Needs more data!

**Comment by KillerKiwiJuice** [comment]
if this is only an issue with chrono-resume I think it can be closed

**Comment by elodea** [comment]
https://github.com/Legion-Expansion/Legion-Expansion/commit/9cc57756b105ec3aa6f838ce90aa12174248c5f4

I think the problem was with the interval being greater than the duration.  Tested and chronocam seemed fine.  For now anyway.

The chronocam problem never happened with the titan bot stomp so i think it's fixed for good now.

**Comment by Quitch** [comment]
Duplicated in my game. Spammed Earthshakers, chronocammed while camera was looking at them. Fucked up camera.

**Comment by Quitch** [comment]
Interferes with #343

**Comment by KillerKiwiJuice** [comment]
I'm pretty sure this is fixed. I tested a lot and never got the issue again.
